- .github/workflows/gh-pages.yml
Previously, after every deployment to gh pages, the CNAME file would be erased requiring someone to manually recreate it in order for sway-playground.org to serve the app. This change simply copies it into the build directory so that it's copied over to the gh-pages branch during deployment.
> Copy CNAME file into build folder

- app/src/constants.ts
- projects/swaypad/src/main.sw
The original example had an initialize counter method which I found confusing as a first time user. The storage variable doesn't need to be "initialized", it can just be used, similar to EVM/Solidity.
The example here is just a simple increment and get, which I believe conforms more to the original counter examples from Solidity while also showcasing read + store, read storage annotation.
> Simplified counter example

- .github/workflows/build-and-test.yml
The deploy workflow for master does the build & test steps first, so there's no need to run this workflow on master.
> Only run test CI once for master

- app/src/components/Copyable.tsx
- app/src/components/shared.tsx
- app/src/features/editor/hooks/useCompile.tsx
- app/src/features/interact/components/ContractInterface.tsx
Previously there was nothing indicating what this hex value is. I've updated it so there's a tooltip over the hex value that tells you what it is, and also made it clickable so users don't have to click the tiny icon to copy it.
Before:
After:
> Improve tooltip for copyable hex

- .gitignore
- README.md
- app/package-lock.json
- app/package.json
- app/src/App.tsx
- app/src/components/SecondaryButton.tsx
- app/src/constants.ts
- app/src/features/editor/components/ActionOverlay.tsx
- app/src/features/editor/components/EditorView.tsx
- app/src/features/editor/components/SolidityEditor.tsx
- app/src/features/editor/components/SwayEditor.tsx
- app/src/features/editor/hooks/useCompile.tsx
- app/src/features/editor/hooks/useTranspile.tsx
- app/src/features/toolbar/components/ActionToolbar.tsx
- app/src/features/toolbar/components/CompileButton.tsx
- app/src/hooks/useIsMobile.tsx
- app/src/utils/localStorage.ts
- deployment/Dockerfile
- src/compilation/mod.rs
- src/compilation/swaypad.rs
- src/main.rs
- src/transpilation/mod.rs
- src/transpilation/solidity.rs
- src/types.rs
- src/util.rs
- disables the deployment button on mobile
- makes the action toolbar wrap so all buttons are on screen
- makes the solidity view stack vertically on mobile
> Make the app responsive on mobile

- .gitignore
- README.md
- app/package-lock.json
- app/package.json
- app/src/App.tsx
- app/src/constants.ts
- app/src/features/editor/components/ActionOverlay.tsx
- app/src/features/editor/components/EditorView.tsx
- app/src/features/editor/components/SolidityEditor.tsx
- app/src/features/editor/components/SwayEditor.tsx
- app/src/features/editor/hooks/useCompile.tsx
- app/src/features/editor/hooks/useTranspile.tsx
- app/src/features/toolbar/components/ActionToolbar.tsx
- app/src/utils/localStorage.ts
- deployment/Dockerfile
- src/compilation/mod.rs
- src/compilation/swaypad.rs
- src/main.rs
- src/transpilation/mod.rs
- src/transpilation/solidity.rs
- src/types.rs
- src/util.rs
Closes https://github.com/FuelLabs/sway-playground/issues/43
Allows users to transpile solidity contracts into Sway and then compile the sway code. Credit to @SilentCicero for the idea!
To test it locally, you'll need to [run the server locally](https://github.com/FuelLabs/sway-playground/blob/master/README.md#running-the-sway-compiler-server) as well as the [frontend](https://github.com/FuelLabs/sway-playground/blob/master/README.md#running-the-frontend), and uncomment the `SERVER_URI` in constants.ts, to point to the local server.
> Support for transpiling Solidity into Sway

- app/src/constants.ts
This patch just fixes the api.sway to prod-2-api.sway URL.
> Emergency patch to fix api.sway-playground to prod-2-api.sway-playgr

- app/src/constants.ts
The domain has been updated to point to the new prod endpoint, so we can change this back.
> Update server endpoint

- app/src/features/editor/components/ActionOverlay.tsx
- app/src/features/editor/components/ExampleDropdown.tsx
- app/src/features/editor/components/ToolchainDropdown.tsx
- app/src/features/editor/examples/solidity/counter.ts
- app/src/features/editor/hooks/useTranspile.tsx
Changes the example selector icon to a dropdown with a label.
mobile:
> Change example dropdown selector

- app/src/features/toolbar/components/ActionToolbar.tsx
Only show the `Interact` button when the contract is deployed. This way we can reduce a button on the toolbar. Eventually deploy can be modified to allow for us to enter an address or deploy it.
> UI Only show Interact button when deployed

- src/types.rs
This ensures only valid toolchains are run in the command line.
> Deserialize toolchain enum rather than string

- .github/workflows/ci.yml
External contributors do not have permission to push to ghcr. To allow external PRs to run all of the workflows, we should only push to ghcr when necessary.
Example: https://github.com/FuelLabs/sway-playground/pull/59
This PR changes the workflow so that we only push to ghcr on merges to master. On PRs, we build the docker image and push to a local registry that can be used in a later step.
> Enable PRs from external forks to pass CI

- app/src/features/toolbar/hooks/useDeployContract.ts
- app/src/utils/metrics.test.ts
- app/src/utils/metrics.ts
- splits up the "user canceled transaction" type errors from the other sdk errors. I suspect that is the majority of deployment errors.
- fixes an issue where deployment errors were tracked twice
- adds the wallet version to the deployment error event
- adds an error log when deployment fails
> Fix deploy metrics

- Cargo.lock
- Cargo.toml
- app/package-lock.json
- app/package.json
- app/src/App.tsx
- app/src/components/Copyable.tsx
- app/src/components/Providers.tsx
- app/src/components/SecondaryButton.tsx
- app/src/features/editor/components/ToolchainDropdown.tsx
- app/src/features/editor/examples/examples.test.ts
- app/src/features/editor/hooks/useGist.tsx
- app/src/features/editor/hooks/useLog.tsx
- app/src/features/editor/hooks/useTranspile.tsx
- app/src/features/toolbar/components/ActionToolbar.tsx
- app/src/index.tsx
- src/compilation/mod.rs
- src/error.rs
- src/gist.rs
- src/main.rs
- src/transpilation/mod.rs
- src/types.rs
Closes https://github.com/FuelLabs/sway-playground/issues/78
Pending devops PR for the new environment variable secret <TODO> 
To test it locally you need the secret as well.
- Adds a share button that, when clicked, generates a link to the playground containing a gist ID, toolchain name, and whether or not the transpile editor should be open.
- The gist includes both the sway code and solidity
- Improves error handling in the other APIs
> feat: Sharable permanent links using gists

- app/src/features/editor/examples/solidity/index.ts
This change removes the ERC20 example from the dropdown list in the Solidity editor.
Currently, the generated sway from the latest version of charcoal for this example does not compile.
The error is: 
```
--> /Users/sophiedankel/Development/sway-playground/projects/swaypad/src/main.sw:20:5
|
18 | 
19 | impl AbiEncode for ERC20Event {
20 |     fn abi_encode(self, buffer: Buffer) {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected: Buffer 
found:    () 
help:     The definition of this function must match the one in the trait "AbiEncode" declaration.
21 |         match self {
22 |             ERC20Event::Approval((a, b, c)) => {
|
____
Aborting due to 1 error.
```
The issue is that the generated code for `abi_encode` does not return a value:
```
fn abi_encode(self, buffer: …
```
> chore: Remove ERC20 solidity example for now.

- app/src/features/interact/components/FunctionToolbar.tsx
- app/src/features/interact/hooks/useCallFunction.ts
Closes https://github.com/FuelLabs/sway-playground/issues/56
Hides the dry run switch for read-only functions, and always calls those functions in dry run mode.
> fix: Always make dry run calls for read only functions

- app/package-lock.json
- app/package.json
- app/src/features/interact/components/ContractInterface.tsx
- app/src/features/interact/components/FunctionInterface.tsx
- app/src/features/interact/components/FunctionToolbar.tsx
- app/src/features/interact/hooks/useCallFunction.ts
- app/src/features/interact/utils/abi.ts
- app/src/features/interact/utils/getTypeInfo.test.ts
- app/src/features/interact/utils/getTypeInfo.ts
- app/src/features/toolbar/hooks/useDeployContract.ts
- deployment/Dockerfile
- projects/swaypad/Forc.toml
Closes https://github.com/FuelLabs/sway-playground/issues/94
Upgrades to the latest version of `fuels` with the new ABI format.
Due to limitations with the new, more complex ABI format, we can no longer support auto-filling nested structs/enums like before. https://fuellabs.slack.com/archives/C01KBNGSWGJ/p1724266226908149
> chore: upgrade fuels to 0.94.0

- app/src/features/editor/examples/sway/multiasset.ts
- app/src/features/editor/examples/sway/singleasset.ts
- projects/swaypad/Forc.toml
- The SRC-20 specs have been updated to include logging for Name, Symbol, Decimals, and Total supply. This has been added to the single and multi asset examples to match the specs.
- The SRC-3 specs have been updated to include an `Option` as part of the `sub_id` argument. The single and multi asset examples have been updated to match the specs
- The Sway-Standards version has been updated to v0.6.1
> Update Single and Multi Asset Example to match latest SRC-20 and SRC-3 specs

- app/src/AbiApp.tsx
- app/src/features/editor/components/AbiEditorView.tsx
- app/src/features/editor/components/JsonEditor.tsx
- app/src/features/toolbar/components/AbiActionToolbar.tsx
- app/src/features/toolbar/components/ActionToolbar.tsx
- app/src/features/toolbar/hooks/useConnectIfNotAlready.ts
- app/src/index.tsx
Closes https://github.com/FuelLabs/sway-playground/issues/101
Adds a new page at `/abi` where users can enter a contract ID, paste an ABI into a text editor and then query the already-deployed contract.
> feat: Add ABI view

- deployment/Dockerfile
Currently the solidity transpiler is failing with `WARNING: no support for delegatecall, this, ASM, strings. Coming soon in future releases.` This PR updates the version to the latest commit.
> fix: update charcoal version

- app/src/constants.ts
There's an issue with the old URI's SSL cert, but the fuel.network cert is working.
Updated the env var here: https://sway-playground-ns7rtk87s-fuel-labs.vercel.app/#
> fix: update server URI to fuel.network

- projects/swaypad/Forc.toml
This PR adds Sway Libs an essential library for most Sway developers to Sway Playground.
> Add sway_libs to sway playground

- README.md
- projects/swaypad/Forc.lock
- projects/swaypad/Forc.toml
This pull request updates the dependencies in the `Forc.toml` file for the `swaypad` project to use newer versions of `standards` and `sway_libs`.
Dependency updates:
* Updated `standards` dependency to version `v0.7.0` from `v0.6.1`.
* Updated `sway_libs` dependency to version `v0.25.1` from `v0.24.0`.
> chore: update Sway libs
